name: Lint protobuf

on:
  push:
    branches: [ master ]
    paths:
      - "**/*.proto"
  pull_request:
    branches: [ master ]
    paths:
      - "**/*.proto"

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.5.0

      - name: Run protolint
        uses: plexsystems/protolint-action@v0.7.0
        with:
          configDirectory: .protolint